lint:
  files_exist:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-access_data_analysis_logo_light.png
  - docs/images/nf-core-access_data_analysis_logo_light.png
  - docs/images/nf-core-access_data_analysis_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  files_unchanged:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-access_data_analysis_logo_light.png
  - docs/images/nf-core-access_data_analysis_logo_light.png
  - docs/images/nf-core-access_data_analysis_logo_dark.png
  - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
  - report_comment
  nextflow_config:
  - manifest.name
  - manifest.homePage
  - validation.help.beforeText
  - validation.help.afterText
  - validation.summary.beforeText
  - validation.summary.afterText
nf_core_version: 3.1.0
repository_type: pipeline
template:
  author: '@shguturu'
  description: access data analysis
  force: true
  is_nfcore: false
  name: access_data_analysis
  org: msk
  outdir: .
  skip_features: []
  version: 1.0.0dev
